#!/bin/sh /etc/rc.common

USE_PROCD=1

start_service() 
  {
echo "starting mesh optimization service"
procd_open_instance
procd_set_param command
procd_set_param file /usr/share/optimizer/mesher.py # /etc/init.d/mesherd reload
  }

reload_service()
    {
        echo "restarting mesher daemon"
        stop
        start
    }

stop_service()
  {
      killall -9 mesher.py
  }